### PR TITLE
feat: Bump pact to 12.0.0

### PR DESCRIPTION
**Pull request by sonallux**
### Checklist

- [x] `npm run dist` all pass on my machine
- [x] I have followed the commit message guidelines, with messages suitable for appearing in the changelog

### Description

Bump `@pact-foundation/pact` to `12.0.0` which was released yesterday.

### CODE REVIEW

**Comment by mefellows** [comment]
Just note that the version change for Pact is likely going to require a similar major version bump, as it releases a breaking change (dropped support for node < 16).

**Comment by sonallux** [comment]
> Thanks for raising this. Just note that the version change for Pact is likely going to require a similar major version bump, as it releases a breaking change (dropped support for node < 16).

Makes sense 👍 I have added a second commit to require at least node 16.

**Comment by YOU54F** [comment]
Released in 0.11.0

https://github.com/pact-foundation/jest-pact/releases/tag/v0.11.0
https://www.npmjs.com/package/jest-pact

Note: I would have expected this to have been a `major` bump 🤷🏾‍♂️

**Comment by mefellows** [comment]
Ah! It's still a `0.x.x` release - this is still considered a pre-release and all bets are off versioning wise

Screenshot 2023-07-11 at 9 48 54 pm

**Comment by YOU54F** [comment]
ahhhhhh gotcha!

well I am kinda 😅 that it doesn't become a major. thanks for clarifying dude

**Pull request merged**
